version: "3.3"

services:
  friends-frontend:
      build: .
      image: friends-frontend
      ports:
      - "80:80"
      depends_on: 
        - api
      

  api:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 8080
    # depends_on:
    #   - authentication-service
    #   - nats
    networks:
      - internal
      - default


  user:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: user
    # depends_on: 
    #   - nats
    networks: 
      - internal
      - default

  ad:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      AD_SERVICE_DNS: EXAMPLE
      SERVICES: ad
    # depends_on: 
    #   -  nats
    networks:
      - internal
      - default

  groupId:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: groupId
    # depends_on:
    #   - mongo
    #   -  nats
    networks:
      - internal
      - default

  create:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: create
    # depends_on:
    #   - mongo
    #   - nats
    networks:
      - internal
      - default

  join:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: join
    # depends_on:
    #   - mongo
    #   - nats
    networks:
      - internal
      - default

  owner:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: owner
    # depends_on:
    #   - outgoing-proxy-service
    #   - nats
    networks:
      - internal
      - default

  mail-builder:
    image: friends.azurecr.io/friends-backend:latest
    env_file: docker-compose.env
    environment:
      SERVICES: mail-builder
    # depends_on:
    #   - mailer-service
    #   - nats
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
