version: "3.3"

services:
  mailer-service:
    container_name: mailer-service
    image: "friends.azurecr.io/mailer-service:latest"
    ports:
      - "8000:8000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      USE_REDIS: "false"
      USE_AUTH: "false"
      MAIL_HOSTS: "smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email,smtp.ethereal.email"
      MAIL_USER: selina.mayert92@ethereal.email
      MAIL_PASS: Mdb6ruZm3TPG7Z6Y28
      MAILER_PORT: 25
      HTTP_SERVER_PORT: 8000
    networks:
      - internal
      - default

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal
      - default
    ports:
      - "27017:27017"

  nats:
    image: nats:2
    networks:
      - internal
      - default
  
  redis:
    image: redis:latest
    networks:
      - internal
      - default

  outgoing-proxy-service:
    image: friends.azurecr.io/spike-proxy-service
    environment:
      MODE: outgoing
      PORT: 8010
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: aXzoxtIFbLVjebyr0~ppCQFxfsv3ZLNkHBrkyfhz
      SPIKE_CLIENT_SECRET: XUneSMVVJhsGfmVPjjGzZgySdH4hmrNKbXGn5Iupjc68R361v_MuRy_XzBOeCnm3dSNWNU_JBsbWUus7UyVXmvj4cO0GW7am11Ex
      SPIKE_URL: https://ospike.northeurope.cloudapp.azure.com/oauAth2/token
      TOKEN_GRANT_TYPE: client_credentials
      USE_REDIS: 'true'
      OUTGOING_SERVICES: '[{"route":"/kartoffel/*","pathRewrite":{"^/kartoffel":""},"target":"http://kartoffel-master.eastus.cloudapp.azure.com:3001","audience":"kartoffel"}]'
    ports:
      - 8010:8000
    networks:
      - internal
      - default

  authentication-service:
    image: friends.azurecr.io/authentication-service
    env_file: docker-compose.env
    environment:
      PORT: 8004
    ports:
      - '8004:8004'
    networks:
      - internal
      - default
    
      
networks:
  internal:

volumes:
  data:
